sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test
after_success:
  - docker build -t tranvancong/multi-client ./client
  - docker build -t tranvancong/multi-nginx ./nginx
  - docker build -t tranvancong/multi-server ./server
  - docker build -t tranvancong/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take able image to push to docker hub
  - docker push tranvancong/multi-client
  - docker push tranvancong/multi-nginx
  - docker push tranvancong/multi-server
  - docker push tranvancong/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-604646145612
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
